import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        // Browser built-ins (individual to avoid clashing with our service names)
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        fetch: "readonly",
        crypto: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        devicePixelRatio: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Error: "readonly",
        Map: "readonly",
        Set: "readonly",
        Uint8Array: "readonly",
        PerformanceObserver: "readonly",
        getComputedStyle: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        Infinity: "readonly",
        // Application modules
        ArenaUtils: "readonly",
        CrowdEngine: "readonly",
        FlowOptimizer: "readonly",
        GeminiService: "readonly",
        MapsService: "readonly",
        FirebaseService: "readonly",
        AccessibilityService: "readonly",
        GoogleCloudService: "readonly",
        App: "readonly",
        firebase: "readonly",
        gtag: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-redeclare": "off",
      "no-console": "off",
      "eqeqeq": "error",
      "curly": ["error", "multi-line"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "strict": ["error", "function"],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
];
